In [1]:
import pandas as pd

from data.make_dataset import load_data
df = load_data("../data/raw/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,No alley access,Reg,Lvl,AllPub,...,0,No pool,No fence,none,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,No alley access,Reg,Lvl,AllPub,...,0,No pool,No fence,none,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,No alley access,IR1,Lvl,AllPub,...,0,No pool,No fence,none,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,No alley access,IR1,Lvl,AllPub,...,0,No pool,No fence,none,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,No alley access,IR1,Lvl,AllPub,...,0,No pool,No fence,none,0,12,2008,WD,Normal,250000

In [2]:
from features.build_features import encode_categorical_data, get_best_correlation_columns

df = encode_categorical_data(df)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3.0,65.0,8450,1.0,1.0,3.0,3.0,0.0,...,0,3.0,4.0,4.0,0,2,2008,8.0,4.0,208500
1,2,20,3.0,80.0,9600,1.0,1.0,3.0,3.0,0.0,...,0,3.0,4.0,4.0,0,5,2007,8.0,4.0,181500
2,3,60,3.0,68.0,11250,1.0,1.0,0.0,3.0,0.0,...,0,3.0,4.0,4.0,0,9,2008,8.0,4.0,223500
3,4,70,3.0,60.0,9550,1.0,1.0,0.0,3.0,0.0,...,0,3.0,4.0,4.0,0,2,2006,8.0,0.0,140000
4,5,60,3.0,84.0,14260,1.0,1.0,0.0,3.0,0.0,...,0,3.0,4.0,4.0,0,12,2008,8.0,4.0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3.0,62.0,7917,1.0,1.0,3.0,3.0,0.0,...,0,3.0,4.0,4.0,0,8,2007,8.0,4.0,175000
1456,1457,20,3.0,85.0,13175,1.0,1.0,3.0,3.0,0.0,...,0,3.0,2.0,4.0,0,2,2010,8.0,4.0,210000
1457,1458,70,3.0,66.0,9042,1.0,1.0,3.0,3.0,0.0,...,0,3.0,0.0,2.0,2500,5,2010,8.0,4.0,266500
1458,1459,20,3.0,68.0,9717,1.0,1.0,3.0,3.0,0.0,...,0,3.0,4.0,4.0,0,4,2010,8.0,4.0,142125
1459,1460,20,3.0,75.0,9937,1.0,1.0,3.0,3.0,0.0,...,0,3.0,4.0,4.0,0,6,2008,8.0,4.0,147500

In [3]:
best_correlation_column = get_best_correlation_columns(df, 'SalePrice', .5)
best_correlation_column

Index(['OverallQual', 'GrLivArea', 'GarageCars', 'ExterQual', 'GarageArea',
       'TotalBsmtSF', '1stFlrSF', 'BsmtQual', 'KitchenQual', 'FullBath',
       'TotRmsAbvGrd', 'YearBuilt', 'YearRemodAdd'],
      dtype='object')

In [5]:
from features.build_features import choose_columns
df = choose_columns(df, best_correlation_column)

df

,OverallQual,GrLivArea,GarageCars,ExterQual,GarageArea,TotalBsmtSF,1stFlrSF,BsmtQual,KitchenQual,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd
0,7,1710,2,2.0,548,856,856,2.0,2.0,2,8,2003,2003
1,6,1262,2,3.0,460,1262,1262,2.0,3.0,2,6,1976,1976
2,7,1786,2,2.0,608,920,920,2.0,2.0,2,6,2001,2002
3,7,1717,3,3.0,642,756,961,4.0,2.0,1,7,1915,1970
4,8,2198,3,2.0,836,1145,1145,2.0,2.0,2,9,2000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,6,1647,2,3.0,460,953,953,2.0,3.0,2,7,1999,2000
1456,6,2073,2,3.0,500,1542,2073,2.0,3.0,2,7,1978,1988
1457,7,2340,1,0.0,252,1152,1188,4.0,2.0,2,9,1941,2006
1458,5,1078,1,3.0,240,1078,1078,4.0,2.0,1,5,1950,1996
1459,5,1256,1,2.0,276,1256,1256,4.0,3.0,1,6,1965,1965